### ISSUE TITLE
Failed to build mmcv ERROR: Could not build wheels for mmcv, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by G-force78** [camenduru/DWPose-colab#3]
Failed to build mmcv
ERROR: Could not build wheels for mmcv, which is required to install pyproject.toml-based projects
Traceback (most recent call last):
  File "/content/mmpose/app.py", line 19, in <module>
    from mmpose.apis import inference_topdown
  File "/content/mmpose/mmpose/apis/__init__.py", line 2, in <module>
    from .inference import (collect_multi_frames, inference_bottomup,
  File "/content/mmpose/mmpose/apis/inference.py", line 16, in <module>
    from mmpose.datasets.datasets.utils import parse_pose_metainfo
  File "/content/mmpose/mmpose/datasets/__init__.py", line 3, in <module>
    from .dataset_wrappers import CombinedDataset
  File "/content/mmpose/mmpose/datasets/dataset_wrappers.py", line 11, in <module>
    from .datasets.utils import parse_pose_metainfo
  File "/content/mmpose/mmpose/datasets/datasets/__init__.py", line 2, in <module>
    from .animal import *  # noqa: F401, F403
  File "/content/mmpose/mmpose/datasets/datasets/animal/__init__.py", line 2, in <module>
    from .animalkingdom_dataset import AnimalKingdomDataset
  File "/content/mmpose/mmpose/datasets/datasets/animal/animalkingdom_dataset.py", line 3, in <module>
    from ..base import BaseCocoStyleDataset
  File "/content/mmpose/mmpose/datasets/datasets/base/__init__.py", line 2, in <module>
    from .base_coco_style_dataset import BaseCocoStyleDataset
  File "/content/mmpose/mmpose/datasets/datasets/base/base_coco_style_dataset.py", line 12, in <module>
    from xtcocotools.coco import COCO
ModuleNotFoundError: No module named 'xtcocotools'

**Comment by 973398769** [comment]
same error

**Comment by 973398769** [comment]
pip3 install xtcocotools
